grpc:
  port: 8001
spring:
  application:
    name: user-service
  datasource:
    driverClassName: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/testdb
    username: postgres
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
